version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.0
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      resources:
        limits:
          memory: 200m
        reservations:
          memory: 20m
  # docker volume create --name pgdata12 -d local
  db:
    image: postgres:12
    volumes:
      - pgdata12:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432
  redis:
    image: redis:3.2.11
    container_name: redis
    ports:
      - 6379:6379
  web:
    build: .
    command: python /code/medium/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - elasticsearch
      - redis
volumes:
  pgdata12:
